In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/content/bank-full.csv")

In [3]:
#this tells shape of the dataset
data.shape

(45211, 17)

In [4]:
#this command show the first 10 rows as default
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [5]:
#As this command suggest it shows last 10 rows of dataset
data.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [6]:
#This command will give basic info of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [7]:
#this gives an detailed information about the dataset
data.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [8]:
#This command will show total count of duplicates are there
data.duplicated().sum()

np.int64(0)

In [9]:
#This will show how many duplicate values are there in dataset
data[data.duplicated()]

Empty DataFrame
Columns: [age, job, marital, education, default, balance, housing, loan, contact, day, month, duration, campaign, pdays, previous, poutcome, y]
Index: []

In [10]:
#This will count how many null values are there in each column
data.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [11]:
#Counts unique values for each column.
data.nunique()

age            77
job            12
marital         3
education       4
default         2
balance      7168
housing         2
loan            2
contact         3
day            31
month          12
duration     1573
campaign       48
pdays         559
previous       41
poutcome        4
y               2
dtype: int64

In [12]:
#shows frequency distribution of unique values in a specified column
data['age'].value_counts()

age
32    2085
31    1996
33    1972
34    1930
35    1894
      ...
95       2
93       2
92       2
88       2
94       1
Name: count, Length: 77, dtype: int64

In [13]:
#making an copy of the dataset
df = data.copy()
df.shape

(45211, 17)

In [15]:
#converting numeric target (yes = 1, no = 0)
df['is_client_subscribed'] = df['y'].apply(lambda x: 1 if x == 'yes' else 0)

In [16]:
#channel mapping (contact column)
df['Marketing_Channel'] = df['contact'].map({
    'cellular': 'Mobile Outreach',
    'telephone': 'Landline Outreach',
    'unknown': 'Unclassified Channel'
})

In [20]:
#funnel stage identification
df['Engaged_Lead'] = df['duration'].apply(lambda x: 1 if x > 60 else 0)
df['Qualified_Lead'] = np.where((df['balance'] > 0) & (df['default'] == 'no'), 1, 0)

In [21]:
#age group segments
def age_bracket(age):
    if age < 30: return "18-29 (Young Adult)"
    elif age <= 50: return "30-50 (Working Class)"
    else: return "50+ (Senior/Retirement)"

df['Age_Group'] = df['age'].apply(age_bracket)

In [22]:
#call duration category
df['Call_Duration_Min'] = df['duration'] / 60

In [23]:
df.to_csv("Updated_bank_data.csv",index=False)